I = double(imread('lena_color.tif'));   %Reading Image
figure;imshow(I./255);
title('Figure1:Lena Color Image');
redChannel = I(:,:,1); % Red channel
greenChannel =I(:,:,2); % Green channel
blueChannel =I(:,:,3); % Blue channel
figure;imshow(redChannel./255);
title('Figure2:Red Channel');
figure;imshow(greenChannel./255);
title('Figure3:Green Channel');
figure;imshow(blueChannel./255);
title('Figure4:Blue Channel');
Y = 0.299 * redChannel + 0.587 * greenChannel + 0.114 * blueChannel;
U = -0.14713 * redChannel - 0.28886 * greenChannel + 0.436 * blueChannel;
V = 0.615 * redChannel - 0.51499 * greenChannel - 0.10001 * blueChannel;
figure;imshow(Y./255);
title('Figure5:Y Channel');
figure;imshow(U./255);
title('Figure6:U Channel');
figure;imshow(V./255);
title('Figure7:V Channel');
redChannel = Y + 1.139834576 * V;
greenChannel = Y -.3946460533 * U -.58060 * V;
blueChannel = Y + 2.032111938 * U;
RGB = cat(3,redChannel,greenChannel,blueChannel)./255;
figure;imshow(RGB); 
title('Figure8: Reconstructed Image');
R_comp=uint8(dct2(redChannel));
G_comp=uint8(dct2(greenChannel));
B_comp=uint8(dct2(blueChannel));
figure;imshow(G_comp); 
title('Figure9: Green DCT Image');
Y_comp=uint8(dct2(Y));
U_comp=uint8(dct2(U));
V_comp=uint8(dct2(V));
R_comp(R_comp <6) = 0;
G_comp(G_comp <6) = 0;
B_comp(B_comp <6) = 0;
Y_comp(Y_comp <6) = 0;
U_comp(U_comp <2) = 0;
V_comp(V_comp <2) = 0;
R_recon=(idct2(double(R_comp)));
G_recon=(idct2(double(G_comp)));
B_recon=(idct2(double(B_comp)));
Y_recon=(idct2(double(Y_comp)));
U_recon=(idct2(double(U_comp)));
V_recon=(idct2(double(V_comp)));
figure;imshow(G_recon./255); 
title('Figure10: IDCT Green Image');
RGB_recon = cat(3,R_recon,G_recon,B_recon)./255;
YUV_recon = cat(3,Y_recon,U_recon,V_recon)./255;
figure;imshow(RGB_recon); 
title('Figure11: Reconstructed Image RGB');
figure;imshow(YUV_recon); 
title('Figure12: Reconstructed Image YUV');
D = abs(I-RGB_recon).^2;
D2= abs(I-YUV_recon).^2;
MSE_rgb = sum(D(:))/numel(I);
MSE_yuv = sum(D2(:))/numel(I);
